import type {Metadata} from "next";
import {Inter} from "next/font/google";

import "./globals.css";
import "@mantine/core/styles.css"
import React, {Suspense} from "react";
import {MantineProvider} from "@mantine/core";
import {ModalsProvider} from '@mantine/modals';
import AppShell from "./AppShell";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
								children,
							}: Readonly<{
	children: React.ReactNode;
}>) {

	return (
		<html lang="en">
		<body className={inter.className}>
		<MantineProvider forceColorScheme={'dark'}>
			<ModalsProvider labels={{
				cancel: "Cancel",
				confirm: "Yes"
			}}>
				<AppShell>
					<Suspense fallback={"Loading..."}>
					{children}
					</Suspense>
				</AppShell>
			</ModalsProvider>
		</MantineProvider>
		</body>
		</html>
	);
}

export const dynamic = 'force-dynamic'
